spring:
  application:
    name: "laba71"
  datasource:
    url: "jdbc:h2:./db/test;AUTO_SERVER=TRUE"
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath:/db/changelog/master.yaml

server:
  port: 9876
  error:
    whitelabel:
      enabled: false
    path: /error
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: info
    com.example.laba71: DEBUG
    org.springframework.web: INFO
    org:
      springframework:
        security: debug
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-5level){blue} %clr([%X{requestId}]){magenta} %clr(%logger{36}){cyan} - %msg%n"
  file:
    path: logs
